# Generated by Django 3.1.1 on 2020-09-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0004_auto_20200930_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='bio',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
